/* Auto-generated by genmsg_cpp for file /home/panayiotis/ros_workspace/ChapticBelt/msg/data.msg */
#ifndef CHAPTICBELT_MESSAGE_DATA_H
#define CHAPTICBELT_MESSAGE_DATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ChapticBelt
{
template <class ContainerAllocator>
struct data_ {
  typedef data_<ContainerAllocator> Type;

  data_()
  : angle(0)
  , distance(0.0)
  {
  }

  data_(const ContainerAllocator& _alloc)
  : angle(0)
  , distance(0.0)
  {
  }

  typedef int32_t _angle_type;
  int32_t angle;

  typedef float _distance_type;
  float distance;


private:
  static const char* __s_getDataType_() { return "ChapticBelt/data"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2b3030ca6b91bda74e68f5fcf33c93e2"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 angle\n\
float32 distance\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, angle);
    ros::serialization::serialize(stream, distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, angle);
    ros::serialization::deserialize(stream, distance);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(angle);
    size += ros::serialization::serializationLength(distance);
    return size;
  }

  typedef boost::shared_ptr< ::ChapticBelt::data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ChapticBelt::data_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct data
typedef  ::ChapticBelt::data_<std::allocator<void> > data;

typedef boost::shared_ptr< ::ChapticBelt::data> dataPtr;
typedef boost::shared_ptr< ::ChapticBelt::data const> dataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ChapticBelt::data_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ChapticBelt::data_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ChapticBelt

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ChapticBelt::data_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ChapticBelt::data_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ChapticBelt::data_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2b3030ca6b91bda74e68f5fcf33c93e2";
  }

  static const char* value(const  ::ChapticBelt::data_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2b3030ca6b91bda7ULL;
  static const uint64_t static_value2 = 0x4e68f5fcf33c93e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ChapticBelt::data_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ChapticBelt/data";
  }

  static const char* value(const  ::ChapticBelt::data_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ChapticBelt::data_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 angle\n\
float32 distance\n\
\n\
";
  }

  static const char* value(const  ::ChapticBelt::data_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ChapticBelt::data_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ChapticBelt::data_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.angle);
    stream.next(m.distance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct data_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ChapticBelt::data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ChapticBelt::data_<ContainerAllocator> & v) 
  {
    s << indent << "angle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CHAPTICBELT_MESSAGE_DATA_H

